dist: bionic
language: python
python:
  - "3.7"
sudo: required
addons:
  hosts:
    - lh
  sauce_connect:
    tunnel_domains: lh
  chrome: stable
env:
  global:
    - secure: EVObCafLubboW7PQ69OhLI9qSMWDUYuL8EvXCX2MsBzlgX1W6cc62IJbKV87EHOnu/2KgHXYNVYN4rmydVbOU+nMHwtryf8+utNcyuDp40kKoNjWhWue++AheXgAjUt1lON4/kiZ5gxEupQeEXDPvP/5LrUuDUEQRwJa6pbivD8=
    - secure: KOpU31rbmwrjGovRX769F9H1/+KdtB5KJfMKIMRZPTeaH/zrlUDaTh9lBOkAFD1S/0nagsrXIUq9e9PJD3pEWze09VUK0mivCl96/ZXFt605UJXSKgWvZNJdRLexzwPhHd/MDzbMqTfrAlN6x9OSA5uIOaGzaQSZjkXjed8IkRk=
    - secure: MWsPYunBeYxPHk5zngCHe6K67FQc6Da9EL17vd2dLEOqePD3VPI+wVdfUDzwkdc7pslM3/JNUroMtCiVkLi7TBNH37hZ5TN1/lG/5kyqobMkm8xLInrrUOhSgvL566nRBb5QMsIMO4+yg7tQHR0EwHHjAOaI0Yw/2F2WgEZN3TU=
    - DOCKER_IMAGE=alectolytic/rpmbuilder
    - COPR_REPOSITORY=Globaleaks
    - COPR_TEST_REPOSITORY=Globaleaks-Test
    - OS_ARCH=x86_64
  matrix:
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=8
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=7
#Tokens order: sauce_username, sauce_token, codacy_project_token
matrix:
  fast_finish: true
  include:
    - env: GLTEST='test' DISTRIBUTION='buster' CODACY=true
    - env: GLTEST='build_and_install' DISTRIBUTION='buster'
    - env: GLTEST='build_and_install' DISTRIBUTION='focal'
    - env: GLTEST='end2end-0' BROWSER='chrome 80'
    - env: GLTEST='end2end-1' BROWSER='firefox 74'
    - env: GLTEST='end2end-2' BROWSER='edge 80'
    - env: GLTEST='end2end-3' BROWSER='ie 11'
    - env: GLTEST='end2end-4' BROWSER='android 10'
  allow_failures:
    - env: GLTEST='end2end-0' BROWSER='chrome 80'
    - env: GLTEST='end2end-1' BROWSER='firefox 74'
    - env: GLTEST='end2end-2' BROWSER='edge 80'
    - env: GLTEST='end2end-3' BROWSER='ie 11'
    - env: GLTEST='end2end-4' BROWSER='android 10'
before_install:
  - nvm install stable
  - nvm use stable
services:
  - docker
install: true
script:
  - $TRAVIS_BUILD_DIR/travis/script.sh
  # RHEL/CentOS Build
  - docker run -v ${PWD}/el:/sources -v ${PWD}:/output:Z -e "SRPM_ONLY=1" ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}
after_success:
  # RHEL/CentOS Build
  - pip install copr-cli simplejson
  - openssl aes-256-cbc -K $encrypted_916af48005ab_key -iv $encrypted_916af48005ab_iv -in .copr.enc -out .copr -d
  - if [ ! -z "${TRAVIS_TAG}" ]; then copr-cli --config .copr build -r ${OS_DIST}-${OS_VERSION}-${OS_ARCH} ${COPR_REPOSITORY} *.src.rpm; fi
  - copr-cli --config .copr build -r ${OS_DIST}-${OS_VERSION}-${OS_ARCH} ${COPR_TEST_REPOSITORY} *.src.rpm
